//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indepandent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.Rcard = new HashSet<Rcard>();
        }
    
        public int CardID { get; set; }
        public string Theme { get; set; }
        public string Card_img { get; set; }
        public string Card_cate { get; set; }
        public string Video { get; set; }
        public int BlockID { get; set; }
        public int userid { get; set; }
        public System.DateTime Cardtime { get; set; }
        public int Rcardnum { get; set; }
        public int priority { get; set; }
        public string Card_comm { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual userinfo userinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rcard> Rcard { get; set; }
    }
}
