//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indepandent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comment()
        {
            this.reply = new HashSet<reply>();
        }
    
        public int commentid { get; set; }
        public int user_id { get; set; }
        public int game_id { get; set; }
        public Nullable<int> download_id { get; set; }
        public string content { get; set; }
        public System.DateTime comment_time { get; set; }
    
        public virtual download download { get; set; }
        public virtual game game { get; set; }
        public virtual userinfo userinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reply> reply { get; set; }
    }
}
