//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indepandent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @new
    {
        public int newID { get; set; }
        public string new_img { get; set; }
        public string newContent { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public int gameid { get; set; }
    
        public virtual game game { get; set; }
    }
}
