//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indepandent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user1
    {
        public string username { get; set; }
        public string usertelephone { get; set; }
        public string useremail { get; set; }
        public string userimg { get; set; }
        public string userpassword { get; set; }
        public string userintro { get; set; }
        public string userrealname { get; set; }
    }
}
