//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indepandent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class userinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userinfo()
        {
            this.ban = new HashSet<ban>();
            this.Card = new HashSet<Card>();
            this.collections = new HashSet<collections>();
            this.comment = new HashSet<comment>();
            this.download = new HashSet<download>();
            this.feedback = new HashSet<feedback>();
            this.game = new HashSet<game>();
            this.orders = new HashSet<orders>();
            this.Rcard = new HashSet<Rcard>();
            this.reply = new HashSet<reply>();
            this.shoppingcart = new HashSet<shoppingcart>();
        }

        public int userid { get; set; }
        [Required(ErrorMessage = "不能为空")]
        [Display(Name = "用户名")]
        public string username { get; set; }
        [Required(ErrorMessage = "不能为空")]
        [StringLength(20, ErrorMessage = "密码不能超过20个字符")]
        [Display(Name = "密码")]
        public string userpassword { get; set; }
        [Required(ErrorMessage = "不能为空")]
        [Display(Name = "确认密码")]
        [Compare("userpassword")]
        public string confirmpassword { get; set; }

        public string userimg { get; set; }
        [Required(ErrorMessage = "不能为空")]
        [Display(Name = "真实姓名")]
        public string userrealname { get; set; }
        [Required(ErrorMessage = "不能为空")]
        [EmailAddress]
        [Display(Name = "邮箱")]
        public string useremail { get; set; }
        [Required(ErrorMessage = "不能为空")]
        [Display(Name = "电话")]
        public string usertelephone { get; set; }
        public string usercondition { get; set; }
        public string userintro { get; set; }
        [Required(ErrorMessage = "不能为空")]
        [Display(Name = "验证码")]
        public string valicode { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ban> ban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<collections> collections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<download> download { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback> feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<game> game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rcard> Rcard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reply> reply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shoppingcart> shoppingcart { get; set; }
    }
}
